### ISSUE TITLE
测试用例集增加复制功能

### ISSUE THREAD

**Issue by valeurliu** [HttpRunner/FasterWeb#10]
测试用例集里面会有很多的接口，有时候会复用其中的一些接口，一个个的再次从api模板拖到用例集太麻烦，建议增加用例集复制功能

**Comment by yinquanwang** [comment]
用例集本来就有复制功能

**Comment by valeurliu** [comment]
> 复

不好意思，描述的不清楚，是在不同的组之间复制，同一个组内是支持的
