### ISSUE TITLE
【BUG】最新版的代码，测试用例中的用例步骤调整顺序时js报错

### ISSUE THREAD

**Issue by robertzhangwenjie** [HttpRunner/FasterWeb#28]
![image](https://user-images.githubusercontent.com/35749198/53481547-6be3de80-3ab8-11e9-9ef6-4d98a6df0e17.png)

**Comment by AzoraLeo** [comment]
这个是可以上下拖动的

**Comment by robertzhangwenjie** [comment]
> 这个是可以上下拖动的

拖动了不生效
