### ISSUE TITLE
更新API模块某个接口内容，但是在自动化测试用例集里面的内容没有更新（只测试了Validate，其他项没有验证）

### ISSUE THREAD

**Issue by Zimucasey** [HttpRunner/FasterWeb#4]

**Comment by yinquanwang** [comment]
API和测试用例集本身是独立的，API作为模板，所以改动测试用例集里面的单个步骤接口不会改变API管理里的api内容

**Comment by lipenglo** [comment]
这样就不对了  测试用例中的独立用例 就应该是每个api本身    改动api 对应设置的用例集合中的对应pai也该被改变！
